insert into cities( cit_name , geom) values('Barcelona', ST_GeographyFromText('SRID=4326;POINT(2.1734 41.3851)'));
insert into cities( cit_name , geom) values('Paris', ST_GeographyFromText('SRID=4326;POINT(2.3522 48.8566)'));
insert into cities( cit_name , geom) values('Amsterdam', ST_GeographyFromText('SRID=4326;POINT(4.9041 52.3676)'));
insert into cities( cit_name , geom) values('Santorini', ST_GeographyFromText('SRID=4326;POINT(25.4615 36.3932)'));
insert into cities( cit_name , geom) values('Dubrovnik', ST_GeographyFromText('SRID=4326;POINT(18.0944 42.6507)'));
insert into cities( cit_name , geom) values('Copenhagen', ST_GeographyFromText('SRID=4326;POINT(12.5683 55.6761)'));
insert into cities( cit_name , geom) values('Lisbon', ST_GeographyFromText('SRID=4326;POINT(-9.2426043 38.7435977)'));
insert into cities( cit_name , geom) values('Vienna', ST_GeographyFromText('SRID=4326;POINT(16.3738 48.2082)'));
insert into cities( cit_name , geom) values('Budapest', ST_GeographyFromText('SRID=4326;POINT(18.5065015 47.4795219)'));,
insert into cities( cit_name , geom) values('Stockholm', ST_GeographyFromText('SRID=4326;POINT(17.8172485 59.326038)')); 
insert into cities( cit_name , geom) values('Munich', ST_GeographyFromText('SRID=4326;POINT(11.2300171 48.1544891)'));
insert into cities( cit_name , geom) values('Edinburgh', ST_GeographyFromText('SRID=4326;POINT(-3.2877387 55.9411809)'));
insert into cities( cit_name , geom) values('Bruges', ST_GeographyFromText('SRID=4326;POINT(3.057302 51.2606675)')); 
insert into cities( cit_name , geom) values('Florence', ST_GeographyFromText('SRID=4326;POINT(11.1585671 43.7799286)'));
insert into cities( cit_name , geom) values('Prague', ST_GeographyFromText('SRID=4326;POINT(14.3008174 50.059553)'));
insert into cities( cit_name , geom) values('Salzburg', ST_GeographyFromText('SRID=4326;POINT(12.9740295 47.8027805)'));
insert into cities( cit_name , geom) values('Tallinn', ST_GeographyFromText('SRID=4326;POINT(24.5734375 59.4715893)'));
insert into cities( cit_name,  geom) values('Reykjavik', ST_GeographyFromText('SRID=4326;POINT(-21.9348418 64.1334671)'));
insert into cities( cit_name , geom) values('Zurick', ST_GeographyFromText('SRID=4326;POINT(8.454335 47.3774122)'));
insert into cities( cit_name, geom) values('Dublin', ST_GeographyFromText('SRID=4326;POINT(-6.4105097 53.3242066)'));
insert into cities( cit_name,  geom) values('Berlin', ST_GeographyFromText('SRID=4326;POINT(13.095099 52.5063862)'));


insert into season(sea_name) values ('Summer');
insert into season(sea_name) values ('Autumn');
insert into season(sea_name) values ('Winter');
insert into season(sea_name) values ('Spring');


insert into cost(cost_name) values ('Cheap');
insert into cost(cost_name) values ('Intermediate');
insert into cost(cost_name) values ('Expensive');

insert into history(hist_name) values ('Medieval');
insert into history(hist_name) values ('Gothic');
insert into history(hist_name) values ('Renaissance');
insert into history(hist_name) values ('Baroque');
insert into history(hist_name) values ('Neoclassical');
insert into history(hist_name) values ('Art Nouveau');
insert into history(hist_name) values ('Modernist');

insert into activity(act_name) values ('Nightlife');
insert into activity(act_name) values ('Green Space');
insert into activity(act_name) values ('Art and culture');
insert into activity(act_name) values ('Cafe culture');
insert into activity(act_name) values ('Water related activities');


insert into sc(sc_cit_id,sc_sea_id) values( 1,1);
insert into sc(sc_cit_id,sc_sea_id) values( 1,4);
insert into sc(sc_cit_id,sc_sea_id) values( 2,1);
insert into sc(sc_cit_id,sc_sea_id) values( 3,1);
insert into sc(sc_cit_id,sc_sea_id) values( 4,1);
insert into sc(sc_cit_id,sc_sea_id) values( 5,1);
insert into sc(sc_cit_id,sc_sea_id) values( 6,1);
insert into sc(sc_cit_id,sc_sea_id) values( 7,1);
insert into sc(sc_cit_id,sc_sea_id) values( 8,1);
insert into sc(sc_cit_id,sc_sea_id) values( 9,1);
insert into sc(sc_cit_id,sc_sea_id) values( 10,1);
insert into sc(sc_cit_id,sc_sea_id) values( 3,4);
insert into sc(sc_cit_id,sc_sea_id) values( 2,4);
insert into sc(sc_cit_id,sc_sea_id) values( 8,4);
insert into sc(sc_cit_id,sc_sea_id) values( 9,4);
insert into sc(sc_cit_id,sc_sea_id) values( 6,4);
insert into sc(sc_cit_id,sc_sea_id) values( 14,4);
insert into sc(sc_cit_id,sc_sea_id) values( 20,4);
insert into sc(sc_cit_id,sc_sea_id) values( 21,4);
insert into sc(sc_cit_id,sc_sea_id) values( 12,4);
insert into sc(sc_cit_id,sc_sea_id) values( 11,2);
insert into sc(sc_cit_id,sc_sea_id) values( 12,2);
insert into sc(sc_cit_id,sc_sea_id) values( 8,2);
insert into sc(sc_cit_id,sc_sea_id) values( 13,2);
insert into sc(sc_cit_id,sc_sea_id) values( 5,2);
insert into sc(sc_cit_id,sc_sea_id) values( 14,2);
insert into sc(sc_cit_id,sc_sea_id) values( 15,2);
insert into sc(sc_cit_id,sc_sea_id) values( 3,2);
insert into sc(sc_cit_id,sc_sea_id) values( 2,2);
insert into sc(sc_cit_id,sc_sea_id) values( 16,2);
insert into sc(sc_cit_id,sc_sea_id) values( 16,3);
insert into sc(sc_cit_id,sc_sea_id) values( 15,3);
insert into sc(sc_cit_id,sc_sea_id) values( 17,3);
insert into sc(sc_cit_id,sc_sea_id) values( 10,3);
insert into sc(sc_cit_id,sc_sea_id) values( 8,3);
insert into sc(sc_cit_id,sc_sea_id) values( 11,3);
insert into sc(sc_cit_id,sc_sea_id) values( 18,3);
insert into sc(sc_cit_id,sc_sea_id) values( 19,3);
insert into sc(sc_cit_id,sc_sea_id) values( 9,3);
insert into sc(sc_cit_id,sc_sea_id) values( 6,3);



insert into ch(ch_cit_id, ch_hist_id) values(1,2);
insert into ch(ch_cit_id, ch_hist_id) values(1,6);
insert into ch(ch_cit_id, ch_hist_id) values(2,2);
insert into ch(ch_cit_id, ch_hist_id) values(2,3);
insert into ch(ch_cit_id, ch_hist_id) values(2,4);
insert into ch(ch_cit_id, ch_hist_id) values(2,6);
insert into ch(ch_cit_id, ch_hist_id) values(3,4);
insert into ch(ch_cit_id, ch_hist_id) values(4,5);
insert into ch(ch_cit_id, ch_hist_id) values(5,2);
insert into ch(ch_cit_id, ch_hist_id) values(5,3);
insert into ch(ch_cit_id, ch_hist_id) values(5,4);
insert into ch(ch_cit_id, ch_hist_id) values(6,3);
insert into ch(ch_cit_id, ch_hist_id) values(6,4);
insert into ch(ch_cit_id, ch_hist_id) values(6,5);
insert into ch(ch_cit_id, ch_hist_id) values(7,2);
insert into ch(ch_cit_id, ch_hist_id) values(7,4);
insert into ch(ch_cit_id, ch_hist_id) values(8,2);
insert into ch(ch_cit_id, ch_hist_id) values(8,4);
insert into ch(ch_cit_id, ch_hist_id) values(8,6);
insert into ch(ch_cit_id, ch_hist_id) values(9,2);
insert into ch(ch_cit_id, ch_hist_id) values(9,3);
insert into ch(ch_cit_id, ch_hist_id) values(9,4);
insert into ch(ch_cit_id, ch_hist_id) values(9,6);
insert into ch(ch_cit_id, ch_hist_id) values(10,1);
insert into ch(ch_cit_id, ch_hist_id) values(10,4);
insert into ch(ch_cit_id, ch_hist_id) values(10,5);
insert into ch(ch_cit_id, ch_hist_id) values(11,2);
insert into ch(ch_cit_id, ch_hist_id) values(11,3);
insert into ch(ch_cit_id, ch_hist_id) values(11,4);
insert into ch(ch_cit_id, ch_hist_id) values(12,1);
insert into ch(ch_cit_id, ch_hist_id) values(13,2);
insert into ch(ch_cit_id, ch_hist_id) values(13,3);
insert into ch(ch_cit_id, ch_hist_id) values(10,1);
insert into ch(ch_cit_id, ch_hist_id) values(10,4);
insert into ch(ch_cit_id, ch_hist_id) values(10,5);
insert into ch(ch_cit_id, ch_hist_id) values(11,2);
insert into ch(ch_cit_id, ch_hist_id) values(11,3);
insert into ch(ch_cit_id, ch_hist_id) values(11,4);
insert into ch(ch_cit_id, ch_hist_id) values(12,1);
insert into ch(ch_cit_id, ch_hist_id) values(13,2);
insert into ch(ch_cit_id, ch_hist_id) values(13,3);
insert into ch(ch_cit_id, ch_hist_id) values(13,4);
insert into ch(ch_cit_id, ch_hist_id) values(14,2);
insert into ch(ch_cit_id, ch_hist_id) values(14,4);
insert into ch(ch_cit_id, ch_hist_id) values(14,3);
insert into ch(ch_cit_id, ch_hist_id) values(15,2);
insert into ch(ch_cit_id, ch_hist_id) values(15,4);
insert into ch(ch_cit_id, ch_hist_id) values(15,3);
insert into ch(ch_cit_id, ch_hist_id) values(16,2);
insert into ch(ch_cit_id, ch_hist_id) values(16,4);
insert into ch(ch_cit_id, ch_hist_id) values(17,2);
insert into ch(ch_cit_id, ch_hist_id) values(17,4);
insert into ch(ch_cit_id, ch_hist_id) values(17,3);
insert into ch(ch_cit_id, ch_hist_id) values(18,1);
insert into ch(ch_cit_id, ch_hist_id) values(19,1);
insert into ch(ch_cit_id, ch_hist_id) values(19,3);
insert into ch(ch_cit_id, ch_hist_id) values(19,4);
insert into ch(ch_cit_id, ch_hist_id) values(20,1);
insert into ch(ch_cit_id, ch_hist_id) values(20,7);
insert into ch(ch_cit_id, ch_hist_id) values(21,2);
insert into ch(ch_cit_id, ch_hist_id) values(21,4);
insert into ch(ch_cit_id, ch_hist_id) values(21,7);



insert into ca(ca_cit_id, ca_act_id) values(1,1);
insert into ca(ca_cit_id, ca_act_id) values(1,2);
insert into ca(ca_cit_id, ca_act_id) values(1,3);
insert into ca(ca_cit_id, ca_act_id) values(1,4);
insert into ca(ca_cit_id, ca_act_id) values(1,5);
insert into ca(ca_cit_id, ca_act_id) values(2,1);
insert into ca(ca_cit_id, ca_act_id) values(2,2);
insert into ca(ca_cit_id, ca_act_id) values(2,3);
insert into ca(ca_cit_id, ca_act_id) values(2,4);
insert into ca(ca_cit_id, ca_act_id) values(3,1);
insert into ca(ca_cit_id, ca_act_id) values(3,2);
insert into ca(ca_cit_id, ca_act_id) values(3,3);
insert into ca(ca_cit_id, ca_act_id) values(3,4);
insert into ca(ca_cit_id, ca_act_id) values(4,5);
insert into ca(ca_cit_id, ca_act_id) values(5,5);
insert into ca(ca_cit_id, ca_act_id) values(6,1);
insert into ca(ca_cit_id, ca_act_id) values(6,2);
insert into ca(ca_cit_id, ca_act_id) values(7,1);
insert into ca(ca_cit_id, ca_act_id) values(7,4);
insert into ca(ca_cit_id, ca_act_id) values(7,5);
insert into ca(ca_cit_id, ca_act_id) values(8,2);
insert into ca(ca_cit_id, ca_act_id) values(8,3);
insert into ca(ca_cit_id, ca_act_id) values(8,4);
insert into ca(ca_cit_id, ca_act_id) values(9,1);
insert into ca(ca_cit_id, ca_act_id) values(9,3);
insert into ca(ca_cit_id, ca_act_id) values(9,4);
insert into ca(ca_cit_id, ca_act_id) values(10,2);
insert into ca(ca_cit_id, ca_act_id) values(10,5);
insert into ca(ca_cit_id, ca_act_id) values(11,2);
insert into ca(ca_cit_id, ca_act_id) values(12,1);
insert into ca(ca_cit_id, ca_act_id) values(12,2);
insert into ca(ca_cit_id, ca_act_id) values(12,3);
insert into ca(ca_cit_id, ca_act_id) values(12,5);
insert into ca(ca_cit_id, ca_act_id) values(13,3);
insert into ca(ca_cit_id, ca_act_id) values(14,3);
insert into ca(ca_cit_id, ca_act_id) values(15,1);
insert into ca(ca_cit_id, ca_act_id) values(15,2);
insert into ca(ca_cit_id, ca_act_id) values(15,3);
insert into ca(ca_cit_id, ca_act_id) values(16,4);
insert into ca(ca_cit_id, ca_act_id) values(16,3);
insert into ca(ca_cit_id, ca_act_id) values(17,2);
insert into ca(ca_cit_id, ca_act_id) values(17,5);
insert into ca(ca_cit_id, ca_act_id) values(18,2);
insert into ca(ca_cit_id, ca_act_id) values(18,5);
insert into ca(ca_cit_id, ca_act_id) values(19,3);
insert into ca(ca_cit_id, ca_act_id) values(20,1);
insert into ca(ca_cit_id, ca_act_id) values(20,3);
insert into ca(ca_cit_id, ca_act_id) values(21,1);
insert into ca(ca_cit_id, ca_act_id) values(21,2);
insert into ca(ca_cit_id, ca_act_id) values(21,3);
insert into ca(ca_cit_id, ca_act_id) values(21,4);
insert into ca(ca_cit_id, ca_act_id) values(21,5);


insert into cc(cc_cit_id, cc_cost_id) values (1, 2);
insert into cc(cc_cit_id, cc_cost_id) values (2, 3);
insert into cc(cc_cit_id, cc_cost_id) values (3, 3);
insert into cc(cc_cit_id, cc_cost_id) values (4, 3);
insert into cc(cc_cit_id, cc_cost_id) values (5, 2);
insert into cc(cc_cit_id, cc_cost_id) values (6, 3);
insert into cc(cc_cit_id, cc_cost_id) values (7, 1);
insert into cc(cc_cit_id, cc_cost_id) values (8, 3);
insert into cc(cc_cit_id, cc_cost_id) values (9, 1);
insert into cc(cc_cit_id, cc_cost_id) values (10, 3);
insert into cc(cc_cit_id, cc_cost_id) values (11, 3);
insert into cc(cc_cit_id, cc_cost_id) values (12, 2);
insert into cc(cc_cit_id, cc_cost_id) values (13, 2);
insert into cc(cc_cit_id, cc_cost_id) values (14, 2);
insert into cc(cc_cit_id, cc_cost_id) values (15, 1);
insert into cc(cc_cit_id, cc_cost_id) values (16, 2);
insert into cc(cc_cit_id, cc_cost_id) values (17, 1);
insert into cc(cc_cit_id, cc_cost_id) values (18, 2);
insert into cc(cc_cit_id, cc_cost_id) values (19, 3);
insert into cc(cc_cit_id, cc_cost_id) values (20, 2);
insert into cc(cc_cit_id, cc_cost_id) values (21, 2);
