insert into cities( cit_name , geom, cit_img, cit_info) values('Barcelona', ST_GeographyFromText('SRID=4326;POINT(2.1734 41.3851)'),'https://images.pexels.com/photos/1388030/pexels-photo-1388030.jpeg?auto=compress&cs=tinysrgb&w=600','Barcelona, a vibrant city in northeastern Spain, captivates visitors with its rich history, stunning architecture, and dynamic atmosphere. From the iconic works of Antoni Gaudí to the bustling streets of the Gothic Quarter, Barcelona offers a harmonious blend of cultural heritage and modernity. With its renowned museums, lively markets, and tantalizing culinary scene, the city is a sensory delight. Whether exploring its architectural marvels, indulging in delicious tapas, or immersing in its vibrant street life, Barcelona exudes a magnetic charm that leaves a lasting impression on all who visit.')
insert into cities( cit_name , geom, cit_img, cit_info) values('Paris', ST_GeographyFromText('SRID=4326;POINT(2.3522 48.8566)'), 'https://images.pexels.com/photos/1308940/pexels-photo-1308940.jpeg?auto=compress&cs=tinysrgb&w=600' , 'Paris, the capital city of France, is renowned as a global center of art, fashion, and culture. It captivates visitors with its romantic charm, iconic landmarks, and vibrant atmosphere. The city`s stunning architecture, from the Gothic Notre-Dame Cathedral to the majestic Eiffel Tower, provides a backdrop of beauty at every turn. Paris is also home to world-class museums, including the Louvre, which houses the enigmatic Mona Lisa, and the Musée d`Orsay, showcasing an extensive collection of Impressionist masterpieces. Strolling along the elegant Champs-Élysées, exploring the bohemian streets of Montmartre, or enjoying a leisurely boat ride along the Seine River are just a few of the countless experiences that Paris offers. With its thriving culinary scene, charming cafes, and picturesque parks, Paris embodies an enchanting mix of history, art, and joie de vivre that continues to inspire and delight visitors from around the world.');
insert into cities( cit_name , geom, cit_img, cit_info) values('Amsterdam', ST_GeographyFromText('SRID=4326;POINT(4.9041 52.3676)'), 'https://images.pexels.com/photos/15512152/pexels-photo-15512152/free-photo-of-ceu-escuro-ceu-noturno-amsterda-amsterdam.jpeg?auto=compress&cs=tinysrgb&w=600', 'Amsterdam, the capital city of the Netherlands, is a charming and culturally rich destination that entices visitors with its picturesque canals, historic architecture, and vibrant atmosphere. Known for its iconic canal network and stunning gabled houses, Amsterdam offers a unique and romantic setting for exploration. The city is home to world-class museums, including the renowned Rijksmuseum and the Van Gogh Museum, showcasing masterpieces from renowned artists. With its welcoming and tolerant ambiance, diverse culinary scene, and thriving nightlife, Amsterdam truly embodies a blend of tradition and modernity, making it a must-visit city for travelers seeking a captivating European experience.');
insert into cities( cit_name , geom, cit_img, cit_info) values('Santorini', ST_GeographyFromText('SRID=4326;POINT(25.4615 36.3932)'), 'https://images.pexels.com/photos/161275/santorini-travel-holidays-vacation-161275.jpeg?auto=compress&cs=tinysrgb&w=600', 'Santorini, a mesmerizing Greek island nestled in the Aegean Sea, enchants visitors with its breathtaking beauty and unique character. Renowned for its iconic whitewashed buildings perched on cliffs overlooking the azure sea, Santorini offers a postcard-perfect landscape that captivates the imagination. The island`s volcanic origin has shaped its distinct beaches, such as the red sand beach in Akrotiri or the black sand beach in Perissa, adding to its allure. Beyond its stunning vistas, Santorini boasts a rich history, evident in its archaeological sites like the ancient city of Akrotiri and the preserved ruins of Thera. With its romantic sunsets, vibrant nightlife, and delectable cuisine, Santorini continues to be a dream destination for those seeking beauty, relaxation, and a touch of Greek island magic.');
insert into cities( cit_name , geom, cit_img, cit_info) values('Dubrovnik', ST_GeographyFromText('SRID=4326;POINT(18.0944 42.6507)'), 'https://images.pexels.com/photos/15564129/pexels-photo-15564129/free-photo-of-praia-litoral-costa-croacia.jpeg?auto=compress&cs=tinysrgb&w=600', 'Dubrovnik, a jewel of the Adriatic Sea, captivates visitors with its timeless beauty and rich historical heritage. Encircled by ancient city walls, this Croatian coastal gem exudes an enchanting atmosphere. Its well-preserved Old Town, a UNESCO World Heritage site, is a maze of narrow cobblestone streets, picturesque squares, and magnificent architecture. Strolling along the iconic Stradun, the main promenade, one can admire elegant palaces, churches, and charming cafes. Dubrovnik`s stunning fortified walls offer panoramic views of the shimmering turquoise sea and the terracotta rooftops below. With its cultural festivals, vibrant markets, and pristine beaches, Dubrovnik effortlessly combines history, culture, and natural beauty, making it an irresistible destination for travelers seeking an unforgettable experience on the Adriatic coast.');
insert into cities( cit_name , geom, cit_img, cit_info) values('Copenhagen', ST_GeographyFromText('SRID=4326;POINT(12.5683 55.6761)'), 'https://images.pexels.com/photos/5193476/pexels-photo-5193476.jpeg?auto=compress&cs=tinysrgb&w=600', 'Copenhagen, the capital city of Denmark, is a captivating blend of Scandinavian charm, modern design, and sustainable living. Known for its bicycle-friendly streets, Copenhagen offers a refreshing and eco-conscious approach to urban living. The city showcases a harmonious mix of historic architecture, such as the colorful Nyhavn waterfront, and contemporary landmarks like the iconic Royal Danish Opera House. Visitors can explore world-class museums like the National Gallery of Denmark, immerse themselves in the cozy atmosphere of the trendy neighborhoods of Nørrebro and Vesterbro, and indulge in the renowned Nordic culinary scene. With its emphasis on innovation, cultural richness, and quality of life, Copenhagen presents a unique and vibrant destination that embodies the best of Danish culture and values.');
insert into cities( cit_name , geom, cit_img, cit_info) values('Lisbon', ST_GeographyFromText('SRID=4326;POINT(-9.2426043 38.7435977)'), 'https://images.pexels.com/photos/1534560/pexels-photo-1534560.jpeg?auto=compress&cs=tinysrgb&w=600', 'Lisbon, the capital city of Portugal, is a captivating destination that effortlessly combines history, charm, and a vibrant atmosphere. Perched on seven hills overlooking the Tagus River, Lisbon offers stunning panoramic views and a rich cultural heritage. The city`s winding streets are adorned with colorful tiles, historic buildings, and quaint neighborhoods like Alfama and Bairro Alto. Lisbon`s iconic landmarks, including the Belem Tower and Jeronimos Monastery, showcase its glorious past as a maritime powerhouse. With its lively markets, lively nightlife, and delicious cuisine, featuring mouthwatering pastries and fresh seafood, Lisbon warmly embraces visitors with its warm Mediterranean spirit, making it a delightful destination for exploration and discovery.');
insert into cities( cit_name , geom, cit_img, cit_info) values('Vienna', ST_GeographyFromText('SRID=4326;POINT(16.3738 48.2082)'), 'https://images.pexels.com/photos/13070414/pexels-photo-13070414.jpeg?auto=compress&cs=tinysrgb&w=600', 'Vienna, the capital city of Austria, is a city of grandeur, elegance, and cultural richness. Known for its opulent palaces, magnificent architecture, and a rich musical heritage, Vienna offers a captivating experience for visitors. The city`s historic center, a UNESCO World Heritage site, is a treasure trove of architectural marvels, including the majestic Schönbrunn Palace and the iconic St. Stephen`s Cathedral. Vienna`s thriving classical music scene, with its prestigious concert halls and opera houses, pays homage to renowned composers such as Mozart, Beethoven, and Strauss. With its charming coffee houses, vibrant markets, and world-class museums, Vienna seamlessly blends tradition with a modern and cosmopolitan flair, making it a destination that delights the senses and leaves a lasting impression.');
insert into cities( cit_name , geom, cit_img, cit_info) values('Budapest', ST_GeographyFromText('SRID=4326;POINT(18.5065015 47.4795219)'), 'https://images.pexels.com/photos/3148096/pexels-photo-3148096.jpeg?auto=compress&cs=tinysrgb&w=600', 'Budapest, the capital city of Hungary, is a captivating metropolis renowned for its stunning architecture, rich history, and vibrant atmosphere. Divided by the Danube River, Budapest offers a harmonious blend of the historic Buda side and the lively Pest side. The city`s iconic landmarks, such as the majestic Hungarian Parliament Building, the Chain Bridge, and the Castle Hill, showcase its grandeur and charm. Budapest`s thermal baths, including the famous Széchenyi Baths, provide relaxation and rejuvenation. The city`s vibrant cultural scene, with its world-class museums, classical music concerts, and bustling ruin bars, creates an electric ambiance that draws visitors in. Budapest`s culinary delights, from traditional Hungarian dishes to innovative gastronomy, further enhance its appeal. With its blend of history, culture, and vibrant energy, Budapest captivates the hearts of travelers and leaves a lasting impression.');
insert into cities( cit_name , geom, cit_img, cit_info) values('Stockholm', ST_GeographyFromText('SRID=4326;POINT(17.8172485 59.326038)'), 'https://images.pexels.com/photos/3030468/pexels-photo-3030468.jpeg?auto=compress&cs=tinysrgb&w=600', 'Stockholm, the capital city of Sweden, is a captivating Nordic gem that seamlessly combines a rich historical heritage with modern Scandinavian design. Spread across 14 islands connected by picturesque bridges, Stockholm offers a breathtaking waterfront setting. The city`s stunning architecture, including the royal palace and the City Hall, stands as a testament to its regal past. Stockholm`s charming old town, Gamla Stan, enchants with its cobblestone streets and colorful buildings. The city`s vibrant cultural scene, with world-class museums like the Vasa Museum and the ABBA Museum, showcases its artistic and musical prowess. Stockholm`s commitment to sustainability, clean air, and outdoor activities is evident in its numerous parks and green spaces. With its culinary delights, fashionable boutiques, and a welcoming atmosphere, Stockholm offers a unique blend of tradition, innovation, and natural beauty that captivates visitors from around the world.'); 
insert into cities( cit_name , geom, cit_img, cit_info) values('Munich', ST_GeographyFromText('SRID=4326;POINT(11.2300171 48.1544891)'), 'https://images.pexels.com/photos/4213372/pexels-photo-4213372.jpeg?auto=compress&cs=tinysrgb&w=600', 'Munich, the capital city of Bavaria in Germany, is a captivating blend of rich history, cultural heritage, and modern vibrancy. Known for its world-famous Oktoberfest, Munich offers a unique combination of traditional Bavarian charm and a thriving cosmopolitan atmosphere. The city boasts stunning architecture, including the iconic Frauenkirche and Nymphenburg Palace, as well as impressive museums like the Alte Pinakothek and the BMW Museum. Munich is a paradise for beer lovers, with its historic beer halls and gardens, where locals and visitors come together to enjoy the city`s brewing traditions. The city also hosts a wealth of cultural events, from classical music concerts to contemporary art exhibitions, ensuring a lively and diverse cultural scene. With its beautiful parks, vibrant markets, and warm Bavarian hospitality, Munich invites travelers to experience its unique blend of history, culture, and a zest for life.');
insert into cities( cit_name , geom, cit_img, cit_info) values('Edinburgh', ST_GeographyFromText('SRID=4326;POINT(-3.2877387 55.9411809)'), 'https://images.pexels.com/photos/4440109/pexels-photo-4440109.jpeg?auto=compress&cs=tinysrgb&w=600', 'Edinburgh, the capital city of Scotland, is a captivating blend of history, culture, and stunning natural beauty. Set against the backdrop of the iconic Edinburgh Castle and the dramatic landscape of Arthur`s Seat, the city offers a charming mix of medieval charm and modern vibrancy. The historic Royal Mile, with its cobblestone streets and hidden closes, leads from the castle down to the Palace of Holyroodhouse. Edinburgh`s rich cultural scene is showcased through its renowned festivals, including the Edinburgh Festival Fringe and the Royal Edinburgh Military Tattoo, which attract artists and performers from around the world. The city is also home to prestigious institutions such as the University of Edinburgh and the National Museum of Scotland, preserving its intellectual and artistic heritage. With its welcoming atmosphere, lively pubs, and a wide range of culinary delights, Edinburgh is a city that delights the senses and leaves a lasting impression on all who visit.');
insert into cities( cit_name , geom, cit_img, cit_info) values('Bruges', ST_GeographyFromText('SRID=4326;POINT(3.057302 51.2606675)'), 'https://images.pexels.com/photos/5215151/pexels-photo-5215151.jpeg?auto=compress&cs=tinysrgb&w=600', 'Bruges, often referred to as the "Venice of the North," is a picturesque medieval city in Belgium that enchants visitors with its fairy-tale-like charm and well-preserved historical treasures. With its meandering canals, cobblestone streets, and beautifully preserved Gothic architecture, Bruges offers a captivating glimpse into the past. The city`s historic center, a UNESCO World Heritage site, is adorned with stunning landmarks such as the towering Belfry of Bruges and the intricate Basilica of the Holy Blood. Bruges is also famous for its delectable Belgian chocolate, flavorful beers, and welcoming cafes where one can indulge in the local culinary delights. With its romantic atmosphere, delightful canal boat rides, and a wealth of art and culture, Bruges is a true gem that transports visitors to a bygone era.'); 
insert into cities( cit_name , geom, cit_img, cit_info) values('Florence', ST_GeographyFromText('SRID=4326;POINT(11.1585671 43.7799286)'), 'https://images.pexels.com/photos/4179480/pexels-photo-4179480.jpeg?auto=compress&cs=tinysrgb&w=600', 'Florence, the birthplace of the Renaissance, is a captivating city in Italy that immerses visitors in a wealth of art, culture, and architectural marvels. Renowned for its iconic Duomo, Florence boasts a breathtaking skyline dominated by stunning Renaissance landmarks. The city`s historic center, a UNESCO World Heritage site, showcases renowned masterpieces such as Michelangelo`s David at the Accademia Gallery and Botticelli`s Birth of Venus at the Uffizi Gallery. Florence`s charming streets, lined with elegant palaces, bustling markets, and picturesque bridges, invite exploration and discovery. With its rich history, vibrant piazzas, and delectable Tuscan cuisine, Florence offers an enchanting experience that celebrates the beauty of art and culture at every turn.');
insert into cities( cit_name , geom, cit_img, cit_info) values('Prague', ST_GeographyFromText('SRID=4326;POINT(14.3008174 50.059553)'), 'https://images.pexels.com/photos/126292/pexels-photo-126292.jpeg?auto=compress&cs=tinysrgb&w=600', ' Prague, the capital city of the Czech Republic, is a captivating destination that exudes a blend of historical grandeur and Bohemian charm. Known as the "City of a Hundred Spires," Prague enchants visitors with its stunning architecture, including the iconic Prague Castle, Charles Bridge, and Old Town Square. Its beautifully preserved medieval old town, a UNESCO World Heritage site, transports visitors back in time with its narrow cobblestone streets and charming buildings. Prague`s rich cultural heritage is evident in its world-class museums, vibrant music scene, and lively festivals. With its cozy cafes, bustling markets, and a thriving craft beer culture, Prague offers a perfect mix of history, culture, and a warm and welcoming atmosphere that captivates the hearts of all who visit.');
insert into cities( cit_name , geom, cit_img, cit_info) values('Salzburg', ST_GeographyFromText('SRID=4326;POINT(12.9740295 47.8027805)'), 'https://images.pexels.com/photos/6148044/pexels-photo-6148044.jpeg?auto=compress&cs=tinysrgb&w=600', 'Salzburg, a charming city nestled in the Austrian Alps, captivates visitors with its enchanting beauty and rich musical heritage. Birthplace of the famous composer Mozart, Salzburg is a city that exudes elegance and cultural splendor. Its picturesque old town, a UNESCO World Heritage site, is a maze of narrow streets, baroque architecture, and charming squares. The city is adorned with magnificent landmarks like the Hohensalzburg Fortress and the Salzburg Cathedral. Salzburg`s music scene comes alive with the world-renowned Salzburg Festival, celebrating classical music and opera. With its stunning alpine backdrop, vibrant markets, and delightful cafes serving traditional Austrian delicacies, Salzburg offers a delightful blend of history, culture, and natural beauty that leaves a lasting impression on all who visit.');
insert into cities( cit_name , geom, cit_img, cit_info) values('Tallinn', ST_GeographyFromText('SRID=4326;POINT(24.5734375 59.4715893)'), 'https://images.pexels.com/photos/15097858/pexels-photo-15097858/free-photo-of-construcao-moderna-predio-moderno-edificio-moderno-arquitetura.jpeg?auto=compress&cs=tinysrgb&w=600', 'Tallinn, the capital city of Estonia, is a charming blend of medieval history and modern innovation. With its well-preserved medieval old town, a UNESCO World Heritage site, Tallinn`s cobblestone streets, towering city walls, and Gothic architecture transport visitors back in time. The city`s picturesque Town Hall Square, surrounded by colorful merchant houses and outdoor cafes, creates a vibrant atmosphere. Tallinn is also known for its thriving digital and entrepreneurial scene, earning it the nickname "e-Estonia." Visitors can explore innovative museums, enjoy a diverse culinary scene, and experience the warmth and hospitality of the locals. With its fascinating blend of old-world charm and forward-thinking spirit, Tallinn offers a unique and captivating destination for travelers seeking a blend of history, culture, and technological advancement.');
insert into cities( cit_name,  geom, cit_img, cit_info) values('Reykjavik', ST_GeographyFromText('SRID=4326;POINT(-21.9348418 64.1334671)'),'https://images.pexels.com/photos/5722817/pexels-photo-5722817.jpeg?auto=compress&cs=tinysrgb&w=600', 'Reykjavik, the capital city of Iceland, is a captivating destination that combines stunning natural landscapes with a vibrant cultural scene. Set against a backdrop of volcanic mountains and the nearby Atlantic Ocean, Reykjavik offers a unique blend of modernity and untamed wilderness. The city`s compact center is filled with colorful buildings, trendy cafes, and thriving art galleries. Reykjavik`s renowned landmarks include the towering Hallgrimskirkja church and the iconic Harpa concert hall. Beyond the city limits, visitors can explore Iceland`s breathtaking natural wonders, such as the geothermal Blue Lagoon, majestic waterfalls, and the mesmerizing Northern Lights. With a strong emphasis on sustainability, a thriving music and arts scene, and a warm and welcoming atmosphere, Reykjavik invites travelers to discover the magic of Iceland in a city that embodies the country`s unique spirit.');
insert into cities( cit_name , geom, cit_img, cit_info) values('Zurick', ST_GeographyFromText('SRID=4326;POINT(8.454335 47.3774122)'), 'https://images.pexels.com/photos/2244429/pexels-photo-2244429.jpeg?auto=compress&cs=tinysrgb&w=600', 'Zurich, the largest city in Switzerland, is a vibrant and cosmopolitan destination that seamlessly blends natural beauty with modern urban living. Located on the banks of Lake Zurich and surrounded by the stunning Swiss Alps, the city offers breathtaking views and a plethora of outdoor activities. Zurich`s historic old town, with its charming narrow streets and well-preserved medieval architecture, invites visitors to wander and explore. The city is renowned for its thriving cultural scene, boasting world-class museums, theaters, and art galleries. Zurich`s reputation as a global financial center is balanced by its commitment to sustainability and quality of life. With its diverse culinary scene, luxury shopping options, and a lively nightlife, Zurich captivates visitors with its blend of natural splendor, cultural richness, and a sophisticated urban atmosphere.');
insert into cities( cit_name, geom, cit_img, cit_info) values('Dublin', ST_GeographyFromText('SRID=4326;POINT(-6.4105097 53.3242066)'), 'https://images.pexels.com/photos/2416653/pexels-photo-2416653.jpeg?auto=compress&cs=tinysrgb&w=600', 'Dublin, the capital city of Ireland, is a vibrant and dynamic destination that celebrates its rich history, literary heritage, and lively pub culture. The city`s charming streets are adorned with Georgian architecture, colorful doors, and historic landmarks such as Dublin Castle and Trinity College. Dublin is a haven for literature enthusiasts, being the birthplace of renowned writers like James Joyce and Oscar Wilde. Visitors can immerse themselves in Irish history and culture at the National Museum of Ireland and enjoy the iconic Book of Kells at Trinity College Library. Dublin`s pub scene is legendary, offering a warm and lively atmosphere where locals and visitors gather to enjoy traditional Irish music, hearty food, and a pint of Guinness. With its friendly locals, bustling markets, and a thriving arts and music scene, Dublin showcases the best of Irish hospitality and leaves a lasting impression on all who experience its unique charm.');
insert into cities( cit_name,  geom, cit_img, cit_info) values('Berlin', ST_GeographyFromText('SRID=4326;POINT(13.095099 52.5063862)'), 'https://images.pexels.com/photos/2871654/pexels-photo-2871654.jpeg?auto=compress&cs=tinysrgb&w=600', 'Berlin, the capital city of Germany, is a vibrant and dynamic metropolis that seamlessly combines a rich historical heritage with a contemporary cultural scene. As a symbol of resilience and transformation, Berlin`s history is palpable in its iconic landmarks such as the Berlin Wall remnants and Checkpoint Charlie. The city`s diverse neighborhoods, from the trendy Mitte to the artistic Friedrichshain, offer a unique blend of architecture, street art, and bustling markets. Berlin`s cultural scene is unparalleled, with world-class museums, galleries, and a thriving music and nightlife culture. The city`s green spaces, like Tiergarten and Tempelhofer Feld, provide ample opportunities for relaxation and recreation. With its cosmopolitan atmosphere, diverse culinary offerings, and a strong sense of creativity and innovation, Berlin is a city that continually reinvents itself, inviting visitors to explore its vibrant and ever-evolving spirit.');

64.7707732,-24.5186077
insert into season(sea_name) values ('Summer');
insert into season(sea_name) values ('Autumn');
insert into season(sea_name) values ('Winter');
insert into season(sea_name) values ('Spring');


insert into cost(cost_name) values ('Cheap');
insert into cost(cost_name) values ('Intermediate');
insert into cost(cost_name) values ('Expensive');

insert into history(hist_name) values ('Medieval');
insert into history(hist_name) values ('Gothic');
insert into history(hist_name) values ('Renaissance');
insert into history(hist_name) values ('Baroque');
insert into history(hist_name) values ('Neoclassical');
insert into history(hist_name) values ('Art Nouveau');
insert into history(hist_name) values ('Modernist');

insert into activity(act_name) values ('Nightlife');
insert into activity(act_name) values ('Green Space');
insert into activity(act_name) values ('Art and culture');
insert into activity(act_name) values ('Cafe culture');
insert into activity(act_name) values ('Water related activities');


insert into sc(sc_cit_id,sc_sea_id) values( 1,1);
insert into sc(sc_cit_id,sc_sea_id) values( 1,4);
insert into sc(sc_cit_id,sc_sea_id) values( 2,1);
insert into sc(sc_cit_id,sc_sea_id) values( 3,1);
insert into sc(sc_cit_id,sc_sea_id) values( 4,1);
insert into sc(sc_cit_id,sc_sea_id) values( 5,1);
insert into sc(sc_cit_id,sc_sea_id) values( 6,1);
insert into sc(sc_cit_id,sc_sea_id) values( 7,1);
insert into sc(sc_cit_id,sc_sea_id) values( 8,1);
insert into sc(sc_cit_id,sc_sea_id) values( 9,1);
insert into sc(sc_cit_id,sc_sea_id) values( 10,1);
insert into sc(sc_cit_id,sc_sea_id) values( 3,4);
insert into sc(sc_cit_id,sc_sea_id) values( 2,4);
insert into sc(sc_cit_id,sc_sea_id) values( 8,4);
insert into sc(sc_cit_id,sc_sea_id) values( 9,4);
insert into sc(sc_cit_id,sc_sea_id) values( 6,4);
insert into sc(sc_cit_id,sc_sea_id) values( 14,4);
insert into sc(sc_cit_id,sc_sea_id) values( 20,4);
insert into sc(sc_cit_id,sc_sea_id) values( 21,4);
insert into sc(sc_cit_id,sc_sea_id) values( 12,4);
insert into sc(sc_cit_id,sc_sea_id) values( 11,2);
insert into sc(sc_cit_id,sc_sea_id) values( 12,2);
insert into sc(sc_cit_id,sc_sea_id) values( 8,2);
insert into sc(sc_cit_id,sc_sea_id) values( 13,2);
insert into sc(sc_cit_id,sc_sea_id) values( 5,2);
insert into sc(sc_cit_id,sc_sea_id) values( 14,2);
insert into sc(sc_cit_id,sc_sea_id) values( 15,2);
insert into sc(sc_cit_id,sc_sea_id) values( 3,2);
insert into sc(sc_cit_id,sc_sea_id) values( 2,2);
insert into sc(sc_cit_id,sc_sea_id) values( 16,2);
insert into sc(sc_cit_id,sc_sea_id) values( 16,3);
insert into sc(sc_cit_id,sc_sea_id) values( 15,3);
insert into sc(sc_cit_id,sc_sea_id) values( 17,3);
insert into sc(sc_cit_id,sc_sea_id) values( 10,3);
insert into sc(sc_cit_id,sc_sea_id) values( 8,3);
insert into sc(sc_cit_id,sc_sea_id) values( 11,3);
insert into sc(sc_cit_id,sc_sea_id) values( 18,3);
insert into sc(sc_cit_id,sc_sea_id) values( 19,3);
insert into sc(sc_cit_id,sc_sea_id) values( 9,3);
insert into sc(sc_cit_id,sc_sea_id) values( 6,3);



insert into ch(ch_cit_id, ch_hist_id) values(1,2);
insert into ch(ch_cit_id, ch_hist_id) values(1,6);
insert into ch(ch_cit_id, ch_hist_id) values(2,2);
insert into ch(ch_cit_id, ch_hist_id) values(2,3);
insert into ch(ch_cit_id, ch_hist_id) values(2,4);
insert into ch(ch_cit_id, ch_hist_id) values(2,6);
insert into ch(ch_cit_id, ch_hist_id) values(3,4);
insert into ch(ch_cit_id, ch_hist_id) values(4,5);
insert into ch(ch_cit_id, ch_hist_id) values(5,2);
insert into ch(ch_cit_id, ch_hist_id) values(5,3);
insert into ch(ch_cit_id, ch_hist_id) values(5,4);
insert into ch(ch_cit_id, ch_hist_id) values(6,3);
insert into ch(ch_cit_id, ch_hist_id) values(6,4);
insert into ch(ch_cit_id, ch_hist_id) values(6,5);
insert into ch(ch_cit_id, ch_hist_id) values(7,2);
insert into ch(ch_cit_id, ch_hist_id) values(7,4);
insert into ch(ch_cit_id, ch_hist_id) values(8,2);
insert into ch(ch_cit_id, ch_hist_id) values(8,4);
insert into ch(ch_cit_id, ch_hist_id) values(8,6);
insert into ch(ch_cit_id, ch_hist_id) values(9,2);
insert into ch(ch_cit_id, ch_hist_id) values(9,3);
insert into ch(ch_cit_id, ch_hist_id) values(9,4);
insert into ch(ch_cit_id, ch_hist_id) values(9,6);
insert into ch(ch_cit_id, ch_hist_id) values(10,1);
insert into ch(ch_cit_id, ch_hist_id) values(10,4);
insert into ch(ch_cit_id, ch_hist_id) values(10,5);
insert into ch(ch_cit_id, ch_hist_id) values(11,2);
insert into ch(ch_cit_id, ch_hist_id) values(11,3);
insert into ch(ch_cit_id, ch_hist_id) values(11,4);
insert into ch(ch_cit_id, ch_hist_id) values(12,1);
insert into ch(ch_cit_id, ch_hist_id) values(13,2);
insert into ch(ch_cit_id, ch_hist_id) values(13,3);
insert into ch(ch_cit_id, ch_hist_id) values(10,1);
insert into ch(ch_cit_id, ch_hist_id) values(10,4);
insert into ch(ch_cit_id, ch_hist_id) values(10,5);
insert into ch(ch_cit_id, ch_hist_id) values(11,2);
insert into ch(ch_cit_id, ch_hist_id) values(11,3);
insert into ch(ch_cit_id, ch_hist_id) values(11,4);
insert into ch(ch_cit_id, ch_hist_id) values(12,1);
insert into ch(ch_cit_id, ch_hist_id) values(13,2);
insert into ch(ch_cit_id, ch_hist_id) values(13,3);
insert into ch(ch_cit_id, ch_hist_id) values(13,4);
insert into ch(ch_cit_id, ch_hist_id) values(14,2);
insert into ch(ch_cit_id, ch_hist_id) values(14,4);
insert into ch(ch_cit_id, ch_hist_id) values(14,3);
insert into ch(ch_cit_id, ch_hist_id) values(15,2);
insert into ch(ch_cit_id, ch_hist_id) values(15,4);
insert into ch(ch_cit_id, ch_hist_id) values(15,3);
insert into ch(ch_cit_id, ch_hist_id) values(16,2);
insert into ch(ch_cit_id, ch_hist_id) values(16,4);
insert into ch(ch_cit_id, ch_hist_id) values(17,2);
insert into ch(ch_cit_id, ch_hist_id) values(17,4);
insert into ch(ch_cit_id, ch_hist_id) values(17,3);
insert into ch(ch_cit_id, ch_hist_id) values(18,1);
insert into ch(ch_cit_id, ch_hist_id) values(19,1);
insert into ch(ch_cit_id, ch_hist_id) values(19,3);
insert into ch(ch_cit_id, ch_hist_id) values(19,4);
insert into ch(ch_cit_id, ch_hist_id) values(20,1);
insert into ch(ch_cit_id, ch_hist_id) values(20,7);
insert into ch(ch_cit_id, ch_hist_id) values(21,2);
insert into ch(ch_cit_id, ch_hist_id) values(21,4);
insert into ch(ch_cit_id, ch_hist_id) values(21,7);



insert into ca(ca_cit_id, ca_act_id) values(1,1);
insert into ca(ca_cit_id, ca_act_id) values(1,2);
insert into ca(ca_cit_id, ca_act_id) values(1,3);
insert into ca(ca_cit_id, ca_act_id) values(1,4);
insert into ca(ca_cit_id, ca_act_id) values(1,5);
insert into ca(ca_cit_id, ca_act_id) values(2,1);
insert into ca(ca_cit_id, ca_act_id) values(2,2);
insert into ca(ca_cit_id, ca_act_id) values(2,3);
insert into ca(ca_cit_id, ca_act_id) values(2,4);
insert into ca(ca_cit_id, ca_act_id) values(3,1);
insert into ca(ca_cit_id, ca_act_id) values(3,2);
insert into ca(ca_cit_id, ca_act_id) values(3,3);
insert into ca(ca_cit_id, ca_act_id) values(3,4);
insert into ca(ca_cit_id, ca_act_id) values(4,5);
insert into ca(ca_cit_id, ca_act_id) values(5,5);
insert into ca(ca_cit_id, ca_act_id) values(6,1);
insert into ca(ca_cit_id, ca_act_id) values(6,2);
insert into ca(ca_cit_id, ca_act_id) values(7,1);
insert into ca(ca_cit_id, ca_act_id) values(7,4);
insert into ca(ca_cit_id, ca_act_id) values(7,5);
insert into ca(ca_cit_id, ca_act_id) values(8,2);
insert into ca(ca_cit_id, ca_act_id) values(8,3);
insert into ca(ca_cit_id, ca_act_id) values(8,4);
insert into ca(ca_cit_id, ca_act_id) values(9,1);
insert into ca(ca_cit_id, ca_act_id) values(9,3);
insert into ca(ca_cit_id, ca_act_id) values(9,4);
insert into ca(ca_cit_id, ca_act_id) values(10,2);
insert into ca(ca_cit_id, ca_act_id) values(10,5);
insert into ca(ca_cit_id, ca_act_id) values(11,2);
insert into ca(ca_cit_id, ca_act_id) values(12,1);
insert into ca(ca_cit_id, ca_act_id) values(12,2);
insert into ca(ca_cit_id, ca_act_id) values(12,3);
insert into ca(ca_cit_id, ca_act_id) values(12,5);
insert into ca(ca_cit_id, ca_act_id) values(13,3);
insert into ca(ca_cit_id, ca_act_id) values(14,3);
insert into ca(ca_cit_id, ca_act_id) values(15,1);
insert into ca(ca_cit_id, ca_act_id) values(15,2);
insert into ca(ca_cit_id, ca_act_id) values(15,3);
insert into ca(ca_cit_id, ca_act_id) values(16,4);
insert into ca(ca_cit_id, ca_act_id) values(16,3);
insert into ca(ca_cit_id, ca_act_id) values(17,2);
insert into ca(ca_cit_id, ca_act_id) values(17,5);
insert into ca(ca_cit_id, ca_act_id) values(18,2);
insert into ca(ca_cit_id, ca_act_id) values(18,5);
insert into ca(ca_cit_id, ca_act_id) values(19,3);
insert into ca(ca_cit_id, ca_act_id) values(20,1);
insert into ca(ca_cit_id, ca_act_id) values(20,3);
insert into ca(ca_cit_id, ca_act_id) values(21,1);
insert into ca(ca_cit_id, ca_act_id) values(21,2);
insert into ca(ca_cit_id, ca_act_id) values(21,3);
insert into ca(ca_cit_id, ca_act_id) values(21,4);
insert into ca(ca_cit_id, ca_act_id) values(21,5);


insert into cc(cc_cit_id, cc_cost_id) values (1, 2);
insert into cc(cc_cit_id, cc_cost_id) values (2, 3);
insert into cc(cc_cit_id, cc_cost_id) values (3, 3);
insert into cc(cc_cit_id, cc_cost_id) values (4, 3);
insert into cc(cc_cit_id, cc_cost_id) values (5, 2);
insert into cc(cc_cit_id, cc_cost_id) values (6, 3);
insert into cc(cc_cit_id, cc_cost_id) values (7, 1);
insert into cc(cc_cit_id, cc_cost_id) values (8, 3);
insert into cc(cc_cit_id, cc_cost_id) values (9, 1);
insert into cc(cc_cit_id, cc_cost_id) values (10, 3);
insert into cc(cc_cit_id, cc_cost_id) values (11, 3);
insert into cc(cc_cit_id, cc_cost_id) values (12, 2);
insert into cc(cc_cit_id, cc_cost_id) values (13, 2);
insert into cc(cc_cit_id, cc_cost_id) values (14, 2);
insert into cc(cc_cit_id, cc_cost_id) values (15, 1);
insert into cc(cc_cit_id, cc_cost_id) values (16, 2);
insert into cc(cc_cit_id, cc_cost_id) values (17, 1);
insert into cc(cc_cit_id, cc_cost_id) values (18, 2);
insert into cc(cc_cit_id, cc_cost_id) values (19, 3);
insert into cc(cc_cit_id, cc_cost_id) values (20, 2);
insert into cc(cc_cit_id, cc_cost_id) values (21, 2);
